decaf-emu/decaf-emu

- src/elf.h
- src/loader.cpp
- src/modules/coreinit/coreinit_thread.cpp
This relocation format is used in RPXes, and can be found, for example, in version 24 of Amiibo Settings.
I don't know where Cafe OS actually populates r0, r2, and r13; I populate it at thread creation.
> loader: add support for EMB_SDA21 relocations

- src/filesystem.h
- src/usermodule.h
This patch fixes two small issues:
- filesystem misinterprets seek to offset 0 as a seek to the end
of file
- UserModule::findSection incorrectly returns the previous section if symbol is at
beginning of section
I don't think the old seek behaviour is correct, because Amiibo Settings (after sort-of implementing FSReadFileAsync by copy pasting FSReadFile) gets stuck trying to decompress a zero length file if it seeked to the end
> Fix two comparison issues:

- src/modules/zlib125/zlib125_core.cpp
Some applications such as Amiibo Settings v24 uses inflateInit_ instead of inflateInit2, and does set the zalloc/zfree/opaque attributes on the zlib stream. This patch implements inflateInit as a wrapper for inflateInit2, and commented out the asserts that checks for no custom allocators in inflate
> zlib125: implement inflateInit_, ignore custom allocators instead of asserting

- src/interpreter.cpp
The threadState pointer may not fit in a 32-bit register
> interpreter: jit_fallback should use 64-bit mov for thread state

- src/main.cpp
add --log-async and --log-level command line parameters
<s>Temporarily disable OSSleepTicks with a message stating that alarms not implemented; stub out FSReadFileAsync by calling FSReadFile
This is enough to run Amiibo Settings to the point where it draws a loading spinner.</s>
> Log config

- src/main.cpp
Whoops.
For some reason the default value isn't being picked up by docopt; manually check if value is not specified and default to trace
> main: fix crash when log level not specified

- src/interpreter/interpreter_integer.cpp
- src/tests/add.s
- src/tests/addc.s
- src/tests/adde.s
- src/tests/addic.s
- src/tests/addis.s
- src/tests/addme.s
- src/tests/and.s
- src/tests/andi.s
- src/tests/branching.s
- src/tests/factorial.s
Tests added in the tests folder, and modified the carry computation in interpreter_integer.cpp
```C++
auto carry = d < a || (d == a && b > 0);
```
The second disjunct is used for instructions such as "add extended", which, using the carry, can make the result of an addition equal to 'a' itself.
> Tests added + new carry computation

- src/modules/coreinit/coreinit_time.cpp
- src/modules/coreinit/coreinit_time.h
Splatoon needs this since it prints out the time at startup; it now runs slightly further - dies on the first OSReceiveMessage call, which crashes since for some reason it passes in (thread + 0x20) as the message queue
> coreinit: implement OSTicksToCalendarTime

- src/modules/coreinit/coreinit_debug.cpp
- src/modules/zlib125/zlib125_core.cpp
The Health and Safety Guide has a bunch of debug OSConsoleWrite calls; was surprised that this wasn't implemented already.
> coreinit: implement OSConsoleWrite

- src/modules/coreinit/coreinit_fs.cpp
For some reason, the file pointer is null if the folder doesn't exist, but it is not null if the folder exists, but the file doesn't. The previous fix for NSMBU made the functions crash if the folder doesn't exist.
> Fix folders not found bug

- src/jit.h
Assuming this is what was actually intended (shl's branch would never actually be executed previously)
> jit: fix a comparison in shiftTo

- src/interpreter/interpreter_float.cpp
- src/interpreter/interpreter_pairedsingle.cpp
add/sub/div use a and b while mul uses a and c. PowerPC is weird like that.
> Interpreter: fix inputs for float multiplies

- src/be_val.h
Puts the object in a valid state when no constructor argument is given. Gets rid of the possibility of arithmetic mistakes on an uninitialized value.
> be_val: Default initialize value member

- src/bitutils.h
Doesn't have the potential to break strict aliasing or alignment requirements this way.
> bitutils: Use memcpy instead of reinterpret_cast for bit_cast

- src/cpu/jit/jit_float.cpp
This was done with implementations ported from Dolphin.
> Add fctiw, fctiwz, frsp, fabs, fnabs, fmr, and fneg to the JIT.

- src/mem/mem.h
`read`/`write` depend on `readNoSwap`/`writeNoSwap`, so the order of declaration must be swapped to allow them to call their respective functions.
`static inline` is redundant - `inline` functions already act as `static` functions would.
> mem.h: function declarations: fix order, remove redundant "static"

- src/main.cpp
This is required by non-MSVC compilers.
> main.cpp: ensure static functions are forward-declared statically

- src/utils/virtual_ptr.h
- src/utils/wfunc_ptr.h
Since it uses byte_swap, this will ensure it doesn't fail to compile due to an external missing include.
> virtual_ptr/wfunc_ptr: Add include for bitutils

- src/utils/bitutils.h
also removes inline from existing constexpr functions, as constexpr also acts as if inline was provided (this is in the standard).
> bitutils: Mark some functions as constexpr

- src/mem/mem.cpp
- src/modules/nn_result.h
Will stifle eventual warnings on compilers other than MSVC.
> Fix initializer list order

- src/gpu/hlsl/hlsl_generator.cpp
These aren't modified in the scope of the function.
> hlsl_generator: Mark some reference variables and parameters const

- src/utils/bitutils.h
_byteswap_u*** is a MSVC intrinsic and is non-portable.
> bitutils: Add Linux and Mac byteswap implementations

- src/cpu/cpu.h
- src/cpu/disassembler.cpp
- src/cpu/instructiondata.h
- src/cpu/interpreter/interpreter_condition.cpp
- src/debugger.h
- src/platform/platform_posix_thread.cpp
- src/utils/crc32.cpp
These header files were implicitly included, to the point where their contents were not able to be found on non-MSVC build systems.
> Explicitly include various header files

- src/modules/coreinit/coreinit_thread.cpp
- src/modules/coreinit/coreinit_thread.h
- src/modules/zlib125/zlib125_core.cpp
`long`'s size can change depending on the platform. On Windows it is always 32-bit, while on other platforms it can be 32-bit or 64-bit depending on the bitness of the OS. To mitigate this problem, use `int32_t` or `uint32_t` instead where appropriate.
> Wrap or change bound functions with `long` return values

- src/cpu/trace.h
The CPP standard forbids named struct declarations in anonymous unions, MSVC allows it however.
> trace.h: don't declare TraceFieldValue::ValueType in anonymous union

- src/cpu/disassembler.cpp
- src/kernelexport.h
- src/loader.cpp
- src/ppcinvoke.h
- src/ppcinvokelog.h
- src/system.cpp
- src/system.h
Also adjusts the API of the system class to use std::string
> system: Get rid of a _strdup usage

- src/mem/mem.cpp
- src/modules/coreinit/coreinit_expheap.cpp
- src/modules/coreinit/coreinit_ghs.cpp
- src/modules/coreinit/coreinit_memheap.cpp
- src/modules/coreinit/coreinit_taskqueue.cpp
If wanted, I can also change over the intentional null pointer dereference to just be std::abort or std::exit.
> Change some zero literals to nullptr

- src/modules/coreinit/coreinit_alarm.cpp
The previous functionality would be analogous to:
```
if ((!alarm->state) == OSAlarmState::Set) {
...
}
```
> coreinit_alarm: apply not to entire if statement, not left side

- .travis.yml
Before merging, make sure to enable the repository on https://travis-ci.org.
> Add .travis.yml for Travis CI builds

- src/cpu/disassembler.cpp
- src/cpu/trace.cpp
- src/debugger.cpp
- src/debugmsg.h
- src/debugnet.cpp
- src/fuzztests.cpp
- src/gpu/latte_decoder.cpp
- src/gpu/latte_disassembler.cpp
- src/gpu/latte_opcodes.h
- src/gpu/latte_shadir.h
- src/gpu/opengl/glsl_alu.cpp
- src/gpu/opengl/glsl_tex.cpp
- src/hardwaretests.cpp
- src/input/input.cpp
- src/modules/coreinit/coreinit_atomic64.cpp
- src/modules/gx2/gx2_enum.h
- src/modules/gx2/gx2_enum_string.cpp
- src/modules/gx2/gx2_enum_string.h
- src/modules/gx2/gx2_event.cpp
- src/modules/gx2/gx2_fetchshader.cpp
- src/modules/gx2/gx2_surface.cpp
Fixes for various warnings reported by Clang.
The missing-case warnings in particular are probably a personal preference sort of thing; I've found them to be useful in the past, but if you think they're more clutter than they're worth, I can revert those changes and just build with -Wno-switch locally. I left a few of those alone where it was clear the logic was still being worked on or the fix would have been too awkward.
> Warning fixes

- src/processor.h
CoreState consists of an atomic_bool which has it's own initializing constructor.
> processor: Remove memset on CoreState struct instance

- src/filesystem/filesystem_host_file.h
- src/filesystem/filesystem_virtual_folderhandle.h
(from clang -Winconsistent-missing-override)
> Fix missing override declarations.

- src/loader.cpp
This avoids a couple of invalid pointer dereferences I ran into while trying to put together a simple RPX to test with.
> Print useful warnings for a couple of ELF errors

- src/modules/coreinit/coreinit_debug.cpp
- src/utils/strutils.h
I put __os_snprintf() in coreinit_debug.cpp since there was already a string formatter there. I'm assuming __os_snprintf() behaves like C snprintf(), though I haven't tested it extensively.
> Add implementation of __os_snprintf(), and fix string formatting.

- src/cpu/interpreter/interpreter_float.cpp
- src/cpu/interpreter/interpreter_loadstore.cpp
- src/cpu/interpreter/interpreter_pairedsingle.cpp
- src/hardwaretests.cpp
It turns out this was fairly non-intrusive; the only real additional complexity is VXISI for fmadd/etc and over/underflow on fres. I was actually able to simplify roundForMultiply() once I discovered that one of the causes of test failures was a bug in Intel's FPU (at least on the Haswell chip I have) causing FMA3 instructions to not raise the underflow exception in certain cases when they should.
There's also one minor result-affecting fix, which is that ppu_estimate_reciprocal() accepted too narrow an exponent range.
Ignoring FPSCR[FR], there are 26 hwtests that still fail. 2 of those are in fres, in which we don't set FPSCR[FI] on a non-over/underflow inaccurate result (to be fair, the manual says that fres leaves FI undefined). The other 24 are in fmsub and fnmsub and are caused by …
> Fix FPSCR behavior.

- src/modules/gx2/gx2_display.cpp
I've verified the return values for TV (at 720p) and DRC with R8_G8_B8_A8 format, so in particular, 864 instead of 854 is correct for the gamepad screen. I didn't check which formats are accepted by the hardware (mostly because I haven't been able to successfully set up a drawing environment yet), so I just wrote a generic function to return bits per pixel for all surface formats; that could probably be moved to some common source file if there are any other functions which need bits/pixel info.
> Calculate proper display buffer sizes in GX2Calc{TV,DRC}Size().

- src/config.cpp
- src/platform/platform_sdl_input.cpp
I saw you fixed getWindowBorderHeight(); there were just a couple other issues. I also set up config.cpp so it defaults to SDL if GLFW is disabled in the build.
> Fix SDL build, and fix configuration defaults when GLFW is disabled.

- src/platform/platform_sdl_ui.cpp
Just a quick thing I noticed while working on scan buffer read/write handling.
> Fix SDL not consistently drawing to both TV and DRC windows.

- src/mem/mem.cpp
- src/platform/platform_fiber.h
- src/platform/platform_posix_fiber.cpp
- src/platform/platform_win_fiber.cpp
- src/processor.cpp
- src/processor.h
I've done this partly to make debugging easier, but also partly as groundwork for another change I'm looking to make which will support code that draws straight to the scan buffer (as my current test program does), by making scan buffers unwritable by default and using a write violation as an indication that the scan buffer memory needs to be copied to the host framebuffer. I am of course open to suggestions on alternate ways to accomplish that, but I figure it should be useful at least for simple experimentation.
@exjam: I don't know offhand what the Windows equivalent of ```sigaction(SIGSEGV, ...)``` is -- any chance you can take care of that? Also, I haven't dug into the details of the scheduler implementation so I'm not sure my code to stop an emulated thread is correct.
> Catch invalid memory accesses in emulated code

- src/modules/coreinit/coreinit_rendezvous.cpp
OSRendezvous contains std::atomic members.
> coreinit_rendezvous: Don't memset non-pod structs

- tools/gfd-tool/gfdtool.cpp
- Namespace gx2:: was missing while referencing identifier GX2Texture in Debug assert.
> Fixed a minor bug during Debug mode compilation.

- src/cpu/interpreter/interpreter_float.cpp
- src/gpu/microcode/latte_disassembler_export.cpp
I've been busy with other things, but just a couple of things I noticed when trying to build the current code. The updateFPRF() change is because recent Clang with -O2 seems to inline the double version of the function, so it's not available to the paired single instruction implementations.
> Fix missing template instantiations and a couple of warnings

- src/libcpu/src/cpu.cpp
- src/libdecaf/src/modules/coreinit/coreinit_fs.cpp
Because std::thread's constructors take copies of the arguments to be
used in the specified function, it is unnecessary to use std::bind to
bind the arguments of the functions to the function call.
> Remove unnecessary usage of std::bind.

- src/libdecaf/src/debugger/debugger_analysis.cpp
This crashes with a null dereference on Linux with Clang/libc++.
It looks like the test against sFuncData.end() is a no-op, but I've left it alone just in case I'm missing something.
> Don't try to decrement past the beginning of a map.

- src/decaf-sdl/decafsdl.h
- src/decaf-sdl/decafsdl_draw.cpp
I don't know if the current behavior is intentional, but antialiasing makes it easier to see details (like small text) on the emulated screens given the default window size.
> decaf-sdl: Antialias scan buffers when drawing them to the window.

- src/decaf-sdl/decafsdl_draw.cpp
The TV and DRC screens each overflowed vertically by 18 pixels.
> decaf-sdl: Fix emulated screens not fitting inside the window.

- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
I noticed this in the process of tracking down why Xenoblade only renders some primitives to the left 768 pixels of the TV screen. This patch doesn't solve that original problem, but it does fix some cases of depth buffers not being fully cleared because a smaller color buffer happened to be attached to GL_FRAMEBUFFER at the same time.
> opengl: Use separate framebuffer objects for clear operations.

- src/libcpu/src/cpu_interrupts.cpp
There is no need to interrupt other cores from libcpu, since the debugger will do so on its own.
> libcpu: Fix debugger selecting wrong core on breakpoint.

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
I'm not at all confident this is the "correct" fix (the GPU might just be fine with drawing to different-sized color buffers simultaneously, which would make things difficult in OpenGL land), but this fixes the Xenoblade boot screen getting cropped due to extra 768x624 color buffers which are masked off by CB_SHADER_MASK at draw time.
FWIW, Xenoblade never seems to call GX2SetColorBuffer with a null buffer address, and it has one function which roughly looks like:
```
void myGX2SetColorBuffer1(GX2ColorBuffer *cb) {
if (cb) {
GX2SetColorBuffer(cb, 1);
GX2SetTargetChannelMasks(15, 15, 0, 0, 0, 0, 0, 0);
} else {
GX2SetTargetChannelMasks(15, 0, 0, 0, 0, 0, 0, 0);
}
}
```
suggesting that masking off a color target is in fact equivalent to setting it to null.
> opengl: Disable color buffers which are masked off at draw time.

- src/libdecaf/src/gpu/microcode/latte_disassembler.h
- src/libdecaf/src/gpu/opengl/glsl2_translate.cpp
The emulator still dies because it can't translate VTX_FETCH, but one step at a time...
> opengl: Fix disassembly of VTX_FETCH instructions in shader comments.

- src/libdecaf/src/modules/coreinit/coreinit_scheduler.cpp
Fixes non-running threads being credited with idle time when a core goes idle.
> coreinit: Update thread switch time even when switching to no thread.

- src/decaf-cli/main.cpp
- src/decaf-sdl/main.cpp
- src/libdecaf/decaf_config.h
- src/libdecaf/src/decaf_config.cpp
- src/libdecaf/src/modules/coreinit/coreinit_time.cpp
Just as a stopgap until there's a way to sync the emulated clock to the emulated CPU.
> Add a --time-scale option to control the emulated clock speed.

- src/decaf-cli/main.cpp
- src/decaf-sdl/main.cpp
- src/libdecaf/decaf_config.h
- src/libdecaf/src/decaf_config.cpp
- src/libdecaf/src/modules/coreinit/coreinit_enum.h
- src/libdecaf/src/modules/coreinit/coreinit_mcp.cpp
Not sure how you feel about #including coreinit_enum.h at higher levels just to get the region enums. Another possibility would be to store it as a string and do the conversion within coreinit::MCP_GetSysProdSettings(), which is a bit slower but I can't imagine that function is a hotspot.
> Make the emulated system region configurable.

- src/libdecaf/CMakeLists.txt
When running a CMake build with sufficient parallelism (e.g. make -j9) in a freshly created build directory, the build will fail because of a missing header:
```
In file included from [...]/decaf-emu/src/libdecaf/src/gpu/opengl/opengl_driver.h:10:
[...]/decaf-emu/libraries/glbinding/source/glbinding/include/glbinding/gl/types.h:4:10: fatal error: 
'glbinding/glbinding_api.h' file not found
#include <glbinding/glbinding_api.h>
```
glbinding_api.h is a generated header, so libdecaf needs an explicit dependency to ensure that the header is available. (It would be nice if we could have a dependency just on the header and not on the entire library, because some of the glbinding sources take forever to compile, but I don't know CMake well enough to say whether that's possible.)
> cmake: Fix build failure with parallel build in fresh directory.

- src/libdecaf/src/kernel/kernel.cpp
Breakpoints are not masked by OSDisableInterrupts(), so if a core was stopped with interrupts disabled, the cpu::this_core::interruptMask() == cpu::INTERRUPT_MASK assertion in coreinit::internal::checkRunningThreadNoLock() would fail when the core resumed.
For me, this triggered sporadically when trying to step in the debugger after hitting a breakpoint.
> kernel: Skip normal interrupt processing for breakpoints.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
Fixes a problem for a shader in Xenoblade. It exports to export 0, but only export 2 is enabled. Because the higher order bits of cb_shader_mask are not masked out, the fact that a higher numbered export is enabled causes the check if the current export is fully masked to fail.
Idk if this is being caused by another issue somewhere (several asserts have to be ignored to get Xenoblade to the point when this shader is compiled), but to me this seems like a bug regardless.
> Mask cb_shader_mask to select only the bits for the current export

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
The fetch shaders were dumping vertex shaders instead.
> Fix dump of fetch shaders

- src/libdecaf/src/modules/gx2/gx2_debug.cpp
This caused it to try to disassemble past the end of the RETURN, resulting in some interesting assembly.
> Fixed GX2DebugDumpShader not disassembling FS as a subroutine

- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
Xenoblade uses some of these. The emulator doesn't yet actually render any 3D scenes so I can't verify that this is correct, but hopefully it's straightforward?
> opengl: Support 3D textures.

- src/libcpu/src/jit/jit.cpp
Based off initialization code, this is actually supposed to be 32 bytes in size.
> jit: Fix an array overrun

- src/libcpu/espresso/espresso_disassembler.cpp
bgt's BI field is `1` rather than `3`
> espresso_disassembler: Fix disassembly naming of bgt

- src/decaf-cli/config.cpp
- src/decaf-sdl/config.cpp
Forgot to include the setting in the serializer when I added it.
(Okay, maybe I lied a little bit about going to sleep)
> Read system::region from config.json.

- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
Shadow samplers require depth-format textures (using color textures is undefined behavior, even if they have the same bit format) and require that the corresponding sampler objects have depth comparison enabled.
> opengl: Fix handling of depth textures.

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_depthbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
This roughly doubles frame rate and cuts the number of calls per frame by a factor of 15 on the Xenoblade title and options screens.
> opengl: Cache current graphics state to avoid redundant GL calls.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_registers.cpp
This doesn't have nearly as big an impact as the last change, but it does reduce the call-per-frame count by about 25%.
> opengl: Avoid redundant GL calls from register setting.

- src/libdecaf/src/gpu/opengl/opengl_surface.cpp
NES Remix creates some 1x1 compressed textures, probably as a bug, so avoid asserting on them.
> Work around compressed textures created with Wx1 or 1xH size.

- src/common/platform_compiler.h
- src/libcpu/src/interpreter/interpreter_pairedsingle.cpp
At the moment there only seems to be one affected function, and the workaround turned out to be just a matter of disabling optimization on the function, so I went ahead and did that, as ugly as it looks.
> interpreter: Work around a stupid LLVM bug.

- src/libcpu/src/jit/jit_vmemruntime.h
Same thing, less potential compiler warnings
> jit_vmemruntime: Add missing override specifiers

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
Fixes the 4th argument to GX2SetColorControl() having no effect (Xenoblade menus use this to suppress color buffer writes while drawing stencil rectangles).
> opengl: Handle color buffer write masking with CB_SPECIAL_DISABLE.

- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
According to apitrace, this fixes Xenoblade model rendering with respect to depth buffers, though it's still not enough to get models actually drawn to the screen.
I didn't attempt to restore the color mask (as I did with the depth mask) because it gets fairly complex due to the interaction between per-buffer masks and the global CB_COLOR_CONTROL mask.
> opengl: Ensure writes are not masked when clearing buffers.

- src/libdecaf/src/modules/gx2/gx2_surface.cpp
As can be seen from GX2SetDepthBuffer().
> gpu: Shift depth buffer addresses by 8 in PM4 packet.

- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
I got slightly overenthusiastic with the caching; we can't skip uploading a dirty texture just because the registers haven't changed. (But we can still skip the GL state updates.)
> opengl: Fix overly aggressive texture upload avoidance.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
Oops.
Also, I noticed Xenoblade reuses the same portion of memory for different sized attribute buffers (as I imagine a lot of games might do), so we could end up with many GL data buffers overlapping the same address. Not sure offhand what the best solution to this is.
> opengl: Fix failure to upload new data when expanding a data buffer.

- src/libdecaf/src/modules/gx2/gx2_clear.cpp
Forgot that clear operations use a separate packet.
> gx2: Shift depth buffer addresses by 8 in PM4 depth-clear packet.

- src/libdecaf/src/kernel/kernel.cpp
Randomly noticed while looking at thread stuff.
> kernel: Fix missing format argument in coreStateToString().

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
GLSL requires a block identifier, not just the keyword "block".
> opengl: Give transform feedback blocks unique names.

- src/libdecaf/src/modules/gx2/gx2_fetchshader.cpp
gx2.rpl sez:
```
01154b58 <GX2InitFetchShaderEx>:
1154b58:       7c 08 02 a6     mflr    r0
1154b5c:       94 21 ff 98     stwu    r1,-104(r1)
1154b60:       90 01 00 6c     stw     r0,108(r1)
1154b64:       7c ea 3b 78     mr      r10,r7
1154b68:       bd e1 00 24     stmw    r15,36(r1)
1154b6c:       7c 7e 1b 78     mr      r30,r3
...
1155264:       80 9e 00 0c     lwz     r4,12(r30)
...
1155278:       80 be 00 08     lwz     r5,8(r30)
115527c:       91 41 00 1c     stw     r10,28(r1)
1155280:       38 60 00 40     li      r3,64
1155284:       93 3e 00 04     stw     r25,4(r30)
1155288:       48 00 23 39     bl      11575c0 <GX2Invalidate>
```
> gx2: Add missing GX2Invalidate() on newly created fetch shaders.

- src/libdecaf/src/gpu/opengl/opengl_surface.cpp
This partly fixes the Xenoblade character creation screen, which renders the world to a surface in RGB mode and then reads from the same surface in SRGB mode; the circular floor is now a real floor instead of a black hole. The remaining problem (white glare) seems to be some sort of HDR math glitch, which I'm still looking into.
> opengl: Exclude degamma from surface key.

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_depthbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
- src/libdecaf/src/gpu/opengl/opengl_surface.cpp
- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
You don't actually want to merge this yet -- bdaaee9 requires 710fc55 from #302 (also on this branch because the following patches are based on it), so it likewise won't compile without #303 merged. #294 is also needed for correct rendering, though the change itself doesn't conflict with anything here.
> opengl: Surface-related fixes.

- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
@brett19: This is a side effect of your new logic to manage differing surface sizes at the same address. I've made this change since we clearly need to render into the active texture, but Xenoblade seems to have a lot of draw operations in which the same surface is both texture and render target, and I don't yet know if it's relying on any special behavior for that case.
> opengl: Configure color/depth buffers after textures.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
The diff looks ugly, but it's really just a few lines added (`if (exp.id == 61) {...} else`) and a bunch of indentation.
> opengl: Handle writes to gl_FragDepth (pixel output 61).

- src/decaf-sdl/config.cpp
- src/decaf-sdl/decafsdl_draw.cpp
- src/libdecaf/decaf_config.h
- src/libdecaf/src/decaf_config.cpp
If you're using the Nvidia driver, you really really want `"debug_filters": [131185]` because SPAM.
> decaf-sdl: Allow filtering out specific OpenGL debug messages by ID.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_pm4.cpp
- src/libdecaf/src/gpu/pm4.h
- src/libdecaf/src/gpu/pm4_format.h
- src/libdecaf/src/modules/gx2/gx2_swap.cpp
GLDriver doesn't actually make use of this yet; I have a separate patch for that, but Brett suggested there were other issues to consider, so I'll file it in a separate PR.
FYI, gx2.rpl implements this by writing the value to what I assume (based on the DCInvalidateRange/DCFlushRange calls that bracket it) is a control block shared with the GPU.
> Pass the swap interval from GX2SetSwapInterval to the graphics driver.

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_surface.cpp
- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
This nearly halved the number of GL calls on the Xenoblade title screen...
> opengl: Avoid unnecessary calls to glTextureParameteri().

- src/libdecaf/src/gpu/opengl/opengl_registers.cpp
The OpenGL API docs for glClipControl explicitly give the example of DirectX as a use case for GL_ZERO_TO_ONE, and Mesa includes the expression S_028810_DX_CLIP_SPACE_DEF(state->clip_halfz) when computing the PA_CL_CLIP_CNTL register value (note the "halfz"), so I suspect the current logic is backwards.
> opengl: Invert handling of DX_CLIP_SPACE_DEF in PA_CL_CLIP_CNTL.

- src/libdecaf/src/gpu/opengl/opengl_registers.cpp
I had to read over the API docs and Mesa code several times to get this straight, but I _think_ the current code is backwards: the GL meaning of "clamp" is that primitives are not clipped and instead the depth values are clamped to the depth buffer range when they're stored. Mesa also has
```
pa_cl_clip_cntl = ... | S_028810_ZCLIP_NEAR_DISABLE(!state->depth_clip) | ...
```
and the note "depth_clip == 0 implies depth clamping is enabled."
> opengl: Invert handling of ZCLIP_NEAR_DISABLE in PA_CL_CLIP_CNTL.

- src/libdecaf/src/gpu/opengl/glsl2_alu_op2.cpp
- src/libdecaf/src/gpu/opengl/glsl2_cf.cpp
- src/libdecaf/src/gpu/opengl/glsl2_translate.h
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
I suspect the way the hardware works wrt early-Z and discard is to disable early-Z whenever the KILL_ENABLE bit is set, but since we know for certain whether the fragment shader calls discard, I've used that knowledge instead. (I don't actually know what the GPU would do if a pixel shader has KILL instructions but the program doesn't set the KILL_ENABLE bit, but I imagine dev-side shader compilers take care of avoiding that.)
Fixes #331.
> opengl: Disable early fragment tests for shaders which use discard.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/pm4.h
- src/libdecaf/src/modules/gx2/gx2_query.cpp
Fixes dynamic objects on Xenoblade title screen not being rendered.
FWIW, Mesa's R600 driver suggests that addrHi has 16 valid bits of address, based on code like:
```
radeon_emit(cs, PKT3(PKT3_EVENT_WRITE, 2, 0));
radeon_emit(cs, EVENT_TYPE(EVENT_TYPE_ZPASS_DONE) | EVENT_INDEX(1));
radeon_emit(cs, va);
radeon_emit(cs, (va >> 32) & 0xFFFF);
```
But I don't know where the 8-bit field width came from, and it'll always be zero on the Wii U anyway, so I haven't touched that.
> gpu: Remove flags from EVENT_WRITE high address word.

- src/libdecaf/src/gpu/opengl/opengl_registers.cpp
> opengl: Don't divide blend color components by 255.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
With this, the Xenoblade title screen renders correctly (finally!):
> opengl: Disable early-Z when alpha tests are enabled.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
- src/libdecaf/src/modules/gx2/gx2_shaders.h
Adds garbage collection of orphaned shader programs as a side effect (because it wasn't really feasible to do this correctly otherwise).
> opengl: Detect changes to shader memory and recreate as appropriate.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
Cuts down the number of NVIDIA shader instructions per bswap32 from 11 to 2 (unpack and swizzle+pack), though I have no idea what the actual performance of those instructions is -- perhaps Nsight could give some, uh... (cough) insight into that...
We could potentially use unpack instructions to directly read some formats like 8_8_8_8 NORM, but that's a bit more involved so holding off on it for now.
> opengl: Use pack/unpack instructions for endian conversion in shaders.

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
Just fixing a bit of laziness on my part, sorry.
> opengl: Avoid unnecessary glDrawBuffers() calls.

- src/libdecaf/src/gpu/opengl/glsl2_alu_reduction.cpp
> opengl: Remove requirement for CUBE to have distinct X/Y/Z inputs.

- src/libdecaf/decaf_graphics.h
- src/libdecaf/decaf_nullgraphicsdriver.h
- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_pm4.cpp
- src/libdecaf/src/modules/coreinit/coreinit_cache.cpp
- src/libdecaf/src/modules/coreinit/coreinit_lockedcache.cpp
This is the counterpart to the DCFlush change. For this, we do need to synchronize with the GPU thread (the data has to actually be available to the CPU when the DCInvalidate handler returns), so I've added back a simplified version of Brett's task code. I ended up using the same dummy buffer method to pump the PM4 loop if necessary; it would be cleaner to have a shared wakeup signal, but that's more involved and requires changes to the queue handling as well, so I think this is good enough for now.
> opengl: Use DCInvalidateRange() as a signal to download data buffers.

- src/libdecaf/src/modules/coreinit/coreinit_device.cpp
Written so 0.0 translates to 128 instead of a potentially unstable value between 127 and 128, though I don't know if that's what hardware does.
> coreinit: Fix uint8_t overflow.

- src/libdecaf/src/modules/snd_core/snd_core_fx.cpp
Xenoblade sets AXFXDelayCallback and AXFXReverbStdCallback as callbacks, so they get called on every audio frame, resulting in massive log spam if they're not stubbed.
> snd_core: Add a few more AXFX stubs.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_resource.cpp
- src/libdecaf/src/gpu/opengl/opengl_resource.h
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
- src/libdecaf/src/gpu/opengl/opengl_surface.cpp
Since resources are not currently expunged when the memory is reused for another purpose, the resource maps grow over time, causing the linear scans in notify{Cpu,Gpu}Flush() and surfaceSync() to consume more and more CPU as time goes on.  This change introduces a ResourceMemoryMap class to keep a sorted list of resource memory endpoints, so the scans can touch exactly those resources that fit the requested memory range without having to iterate over every single allocated resource.
This gives me around a 3x speedup in Xenoblade after the intro scene.
> opengl: Use a sorted resource map to optimize resource updates.

- src/decaf-sdl/config.cpp
- src/decaf-sdl/config.h
- src/decaf-sdl/decafsdl_sound.cpp
And make it depend on audio output rate.
Default value is 30 so with a 48kHz sample rate, the actual frame length becomes 30x48 = 1440 bytes.
Also change the default which used to be 1024, which on my system was too low and produced flickering sound.
> sdl: Make audio frame length configurable

- src/libcpu/src/jit/binrec/jit_binrec.cpp
- src/libcpu/src/jit/binrec/jit_binrec.h
- src/libcpu/src/jit/jit_codecache.cpp
- src/libcpu/src/jit/jit_codecache.h
This reduces overall CPU usage by around 2% in my tests.
> jit: Inline code block lookups in the execution loop.

- src/decaf-sdl/decafsdl_sound.cpp
If the actual output frame size is different from the requested size, the audio callback would overrun the read buffer and crash with an assertion failure. Regression introduced in 2625308, which made the frame size not be a power of two (Linux requires a power-of-two size).
Also sanity-check the other audio parameters returned by SDL_OpenAudio.
> decaf-sdl: Fix crash when the system changes the audio frame size.

- src/decaf-sdl/decafsdl_opengl.cpp
- tools/pm4-replay/sdl_window_draw.cpp
Enabling the callback introduces significant overhead; I've observed slowdown of up to 35% in GPU-bound code, with the GPU thread spending over 15% of its time just in malloc() and free() calls from glbinding.
> Only enable the glbinding command callback when debugging.

- src/common/src/platform_posix_memory.cpp
The previous code checked if the mapped address (result) matches the desired address (baseAddress). If it does not match, the previous code attempted to unmap the desired address rather than the mapped address.
This fix unmaps the mapped address.
> Fix munmap of incorrect address.

- src/decaf-sdl/decafsdl_opengl.cpp
- tools/pm4-replay/sdl_window_draw.cpp
GL_CLAMP is not a valid GL_TEXTURE_WRAP_ value. See https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glSamplerParameter.xhtml
> Fix copy and paste error (change _S to _T) and use GL_CLAMP_TO_EDGE.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_streamout.cpp
The previous implementation had huge overhead (I measured a frame rate drop of close to 50% in Xenoblade) and wrapped several operations which arguably don't need wrapping, such as simple data writes.
> Reimplement GPU synchronization.

- README.md
- src/decaf-cli/main.cpp
- src/decaf-sdl/config.cpp
- src/decaf-sdl/main.cpp
- src/libdecaf/decaf_config.h
- src/libdecaf/src/debugger/debugger_ui_manager.cpp
- src/libdecaf/src/decaf_config.cpp
- src/libdecaf/src/modules/coreinit/coreinit_shared.cpp
This allows the program to be run from outside the Decaf source tree.
The path can also be set with --resources-path on the command line.
Also remove the unused "--sys-path" option from the command line
option list.
> Add a configuration option to set the path to the resources directory.

- README.md
- src/common/src/platform_posix_memory.cpp
The amount of memory available for shm objects is limited on some
systems, so use a normal file instead of an shm object as the backing
store for emulated memory.
Also document the cause and workaround for SIGBUS crashes.
> posix: Use TMPDIR instead of shm_open for memory backing files.

- libraries/CMakeLists.txt
It doesn't seem to be used anywhere, as code compiles just fine without it. Decaf should now run on older versions of Windows.
> CMake: remove Mincore dependency

- src/libdecaf/src/ppcutils/va_list.h
The ```nextFpr``` function increments the wrong counter.
Ready to be reviewed & merged.
> ppcutils/va_list: Increment FPR counter

- README.md
Previously, this link was completely incorrect. Should be fixed now.
> Fix the Windows binary link

- tools/pm4-replay-qt/replay.cpp
Hi there, I was checking the project out of interest, and found if DECAF_QT was enabled, pm4-replay-qt would fail to compile (on windows). I believe I resolved the issue but I just started looking at the code, so please check if my fix is correct.
> Compile fix for pm4-replay-qt

- src/libgpu/src/spirv/spirv_cf.cpp
- src/libgpu/src/vulkan/vulkan_driver.h
- src/libgpu/src/vulkan/vulkan_memcache.cpp
- src/libgpu/src/vulkan/vulkan_staging.cpp
- src/libgpu/src/vulkan/vulkan_surface.cpp
vulkan: Minor compilation fixes and one possible bug
Do not take address of temporaries.
Use proper casts when casting from Vulkan-Hpp to Vulkan.
Fix use of implicit conversions that make gcc not like it
due to overload ambiguity.
Remove unused bool cast operator, that called non existing
bool operator in other class.
Tested with vulkan 1.1.82 and 1.1.73, and gcc 8.2.
> vulkan: Minor compilation fixes and one possible bug

- src/libgpu/src/vulkan/vulkan_driver.cpp
- src/libgpu/src/vulkan/vulkan_driver.h
- src/libgpu/src/vulkan/vulkan_memcache.cpp
- src/libgpu/src/vulkan/vulkan_staging.cpp
Just convert VkResult into vk::Result using Vulkan-Hpp library.
It will throw exception, if not a success.
Construct a message by using filename and line number.
These errors were previously ignored and lost.
> vulkan: Check results from AMD Vulkan Memory Allocator

- src/libdecaf/src/cafe/libraries/cafe_hle_library.cpp
This improves clarity of the code, by not using pair.second.
Similar construct is already used in cafe_hle_library.h
> cafe/hle: Unpack name and symbol in when for looping over mSymbolMap

- src/libgpu/src/vulkan/vulkan_driver.cpp
- src/libgpu/src/vulkan/vulkan_streamout.cpp
> vulkan: Don't take the address of temporaries.

- src/decaf-qt/settings.cpp
- src/libconfig/src/loader_toml.cpp
When I clicked the apply settings buttons, decaf would crash if it failed to parse my config file.  When this happens I just create a new table.
>  Fixed a crash that occurred when applying settings.

- src/common/bitfield.h
Use a union for bitfields when DECAF_USE_STDLAYOUT_BITFIELD is defined
Previous behavior was to use a struct.  This was causing be2_array
instantiations to use be2_struct for be2_array_item_type instead of be2_val.
The upshot of this was that on Linux builds, byte order would be reversed for
bitfields wrapped in be2_array because be2_struct doesn't do endian reversal.
When DECAF_USE_STDLAYOUT_BITFIELD is not defined, bitfields were already unions,
which is why this behavior did not manifest on Windows.
This commit resolves several programs which were working on Windows but not
Linux and also addresses issue #537 on github.
> fix bitfield byte orders on linux

- src/libdecaf/src/vfs/vfs_host_device.cpp
SAVEInitSaveDir wants to create a directory hierarchy under usr/save/...
on Linux the create_directory call will fail because it only lets you create one directory at a time, so use create_directories instead.
This was not a problem on Windows because the /std:c++latest compiler option causes create_directory to behave the same as create_directories.
This commit fixes NES and SNES vc games which were working on Windows but not Linux.
> vfs: fix makeFolder failure on GNU/Linux

- src/libgpu/src/vulkan/vulkan_driver.cpp
Otherwise, debug builds will fail this assert in the init function:
assert(!!device == !!getDeviceProcAddr);
> Vulkan: pass vkGetDeviceProcAddr to vk::DispatchLoaderDynamic::init

- src/common/decaf_assert.h
Heyo!
This simple patch for #562 to bring decaf's assert more in line with the usual behaviour:
> assert() shall write information about the particular call that failed on stderr and shall call abort().
(that's `man 3p assert`)
`__builtin_trap` on gcc can [either call abort or execute an undefined instruction](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html#index-_005f_005fbuiltin_005ftrap), and in my case it was generating an undefined instruction, causing SIGILL, which would find its way to the illegal instruction handler in cpu_host_exception.cpp, which calls decaf_host_fault - one of the assertions that calls __builtin_trap. Quite the loop!
Using abort causes gdb to break (if attached), and also triggers the KDE bugreporting tool; which generates quite a nice backtrace. Haven't …
> Use abort instead of __builtin_trap on POSIX platforms when assertion fails

- src/decaf-qt/src/settings/contentsettingswidget.cpp
the case-sensitivity of the include-statement didn't match the case-sensitivity
of the file.
> fix linux build

- src/libdecaf/decaf_config.h
My trace filters didn't work until I noticed that I have to add the .rpl extension to the library names. Would have prevented some confusion if the default trace filters were correct.
> libdecaf: Fix lib name in default trace filters

- src/common/log.h
I had to include this header to compile decaf on my machine.
> common: Add missing <memory> include to log.h

- src/libdecaf/src/cafe/libraries/coreinit/coreinit_osreport.cpp
A lot of garbage is printed right now.
> cafe/coreinit: Fix buffer size in OSPanic

- src/libdecaf/src/ios/mcp/ios_mcp_mcp_device.cpp
I saw the following line in the log: `[08:49:51.880345 info:decaf] No title update found at /vol/storage_mlc01/usr/title/0005000e/fffffffd`
I don't think that's the intended behavior.
> ios/mcp: Update title id in mcpPrepareTitle52 if it is DefaultTitleId.

- .github/workflows/ccpp.yml
Since all platforms are being built, may as well upload the binaries. Should make it easier to get a hold of latte-assembler.
Only possible breakage is that the Windows build artifact is now called `decaf-emu-windows-cl` rather than `decaf-emu-windows`.
> ci: Upload artifacts for all platforms

- src/libgpu/src/vulkan/vulkan_display.cpp
Around January, vulkan.hpp changed some key functions to be `noexcept`, including `vk::Device::acquireNextImageKHR` and `vk::Queue::presentKHR` ([commit](https://github.com/KhronosGroup/Vulkan-Hpp/commit/e49f02013a5cf32c14e2f912e16e4fa181c8223a)). Decaf checked for swapchain out-of-date conditions with try/catch, which doesn't work on Vulkan SDK versions with this header.
Tested OK on Vulkan SDK 1.2.154.0, linux, mesa 20.2 (selfbuild).
> libgpu: check return codes, not exceptions, for noexcept vulkan funcs

- .github/workflows/ccpp.yml
- CMakeLists.txt
- README.md
- src/libgpu/src/vulkan/vulkan_display.cpp
- tests/gpu/tiling/vulkan_helpers.cpp
VK_LAYER_LUNARG_standard_validation was deprecated in Vulkan 1.1.106.0 and replaced by  VK_LAYER_KHRONOS_validation. The CI already uses Vulkan 1.2x but when running locally with up to date packages, validation errors occur since the standard_validation is not included in latest Vulkan versions anymore (at least on my machine).
Since VK_LAYER_KHRONOS_validation was introduced after 1.1.92.1, the minimum required version also had to be bumped. I take it this is not an issue though since 1.1.108 is more than one and a half years old by now
Also includes CI fixes for the recent [set-env deprecation](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) and [XCode11 deprecation](https://github.com/actions/virtual-environments/issues/1688)
> Replace deprecated Vulkan validation

- src/decaf-qt/src/mainwindow.cpp
- src/decaf-qt/src/mainwindow.h
Fix
QObject::connect: No such slot MainWindow::toggleFullScreen()
QObject::connect:  (sender name:   'actionViewFullScreen')
QObject::connect:  (receiver name: 'MainWindow')
> Fix QObject::connect: No such slot MainWindow::toggleFullScreen()

- src/libdecaf/src/cafe/libraries/sndcore2/sndcore2_device.cpp
One of the codepaths through the final mix callback would zero 2/3 of the samples before outputting them, which is exciting.
Two patches - one to not zero the samples, and one to let the final mix callback see all the samples, not just 2/3.
Restores audio to Mario Kart 8 and fixes corruption in PUYOPUYOTETRIS. I still get some crunchiness on the audio but that could be my OS not liking when the framerate drops; haven't chased it.
Needs testing on Windows
> Audio fixes for 32kHz games

- src/libdecaf/src/cafe/libraries/sndcore2/sndcore2_device.cpp
Looks like this code came from [BrawlLib](https://github.com/libertyernie/brawltools/blob/master/BrawlLib/Wii/Audio/ADPCMState.cs#L68-L71); but has its condition flipped?
Fix makes Mario Kart 8 sound much better.
> cafe/sndcore2: Fix ADPCM decoding

- src/libdecaf/src/cafe/libraries/gx2/gx2_registers.cpp
Hyrule Warriors calls with garbage values, the original gx2 code does an &1 
to solve that.
Allows Hyrule warriors to get a little further, before a rather mystifying stack/heap corruption issue appears instead.
> cafe/gx2: Sanitise frontFace in GX2InitPolygonControlReg

- README.md
Yet Another Readme PR, sorry. This changes the readme instructions to filter out the action runs to only include successful builds on `master`. The section mentions all 3 OSes now, with Linux's state being changed to reflect it now having binaries.
GitHub does not provide a way for users to download the latest artifact from one link. This appears to be achievable via https://nightly.link/, but that would be outside of the scope of this PR.
> Clarify artifact downloads

- CMakeModules/FindFFMPEG.cmake
Apparently some distros put it here instead - maybe this should use pkg-config eventually? Though I guess you have other plans with vcpkg.
I usually just disabled ffmpeg but it's a hard dependency now.
> cmake: Add hint for ffmpeg headers on Linux

- src/libdecaf/src/cafe/libraries/h264/h264_decode_ffmpeg.cpp
Updates to the newer `av_packet_alloc` API, which removes some deprecation warnings. Also changes the flushing behavior - more details in the commit text - which fixes video playback in Mario Kart 8.
> cafe/h264: Update ffmpeg api and fix flushing behaviour.

- src/libdecaf/src/cafe/libraries/sndcore2/sndcore2_device.cpp
- src/libdecaf/src/cafe/libraries/sndcore2/sndcore2_voice.cpp
- src/libdecaf/src/cafe/libraries/sndcore2/sndcore2_voice.h
Adds "ADSR" (actually just per-voice volume scaling) emulation, which significantly improves audio in NSMBU and Mario Kart 8 (the engine sounds specifically). Not much to say, the code is self-explanatory, and unlike my attempts to implement the filters, I know this is correct~
> cafe/sndcore2: Implement voice ADSR

- tools/latte-assembler/src/assembler_cf.cpp
`ADDR` is needed to specify the target address for `JUMP` instructions.
`POP_CNT` can be used on control flow instructions to pop the pixel state from the stack.
> latte-assembler: Support POP_CNT and ADDR for control flow instructions

- src/libcpu/cpu_control.h
- src/libcpu/src/interpreter/interpreter_system.cpp
- src/libdecaf/src/cafe/kernel/cafe_kernel_exception.cpp
Basically this PR stems from me hitting a bad SPR and wondering why it didn't pop open the debugger.
These patches add a new interrupt for program exceptions, add code to the mtspr/mfspr paths in the interpreter to trigger it, and a little code to the Cafe kernel to forward it through to the default exception handler.
The only handled case is a bad SPR number, if this works then later on things like instruction decoding failures can be handled this way too. This is a kinda minimal, notably it *does not set* any of the SRR1 details about exactly what went wrong.
If this is the wrong way to go about this, feel free to let me know. I think something is amiss - the register dump printed on the terminal is wrong - but the debugger does work as expected.
> cpu: Add program exceptions for bad SPRs in the interpreter

- src/libdecaf/src/ios/kernel/ios_kernel_heap.cpp
This fixes two small mismatches I noticed when comparing against the IOSU implementation.
> ios/kernel: Improve `IOS_HeapRealloc`  
