- src/modules/coreinit/coreinit_fs.cpp
Could you add this to the main branch?
> Fix file bug with good()

- src/cpu/interpreter/interpreter_condition.cpp
Already checked against a little further down.
> interpreter_condition: Remove unused variable

- CMakeLists.txt
- src/filesystem/filesystem.h
- src/main.cpp
- src/platform/platform_posix_memorymap.cpp
Just enough to get the project to build and run hwtests. Hope I'm not getting in the way!
> Linux build/startup fixes

- src/kernelfunction.h
- src/modules/CMakeLists.txt
- src/modules/coreinit/coreinit.cpp
- src/modules/coreinit/coreinit.h
- src/modules/coreinit/coreinit_exit.cpp
- src/modules/coreinit/coreinit_exit.h
Just so my test RPX runs correctly. I didn't see an obvious source file to put these in, so I added a new one.
> Trivial implemetations of _Exit() and OSFatal().

- src/gpu/opengl/glsl_generator.cpp
- src/modules/gx2/gx2_addrlib.cpp
I don't want to get in the way of GX2 work, but just a couple of (hopefully) unintrusive warning fixes.
> Warning fixes.

- .travis.yml
- CMakeLists.txt
- src/CMakeLists.txt
- src/config.cpp
- src/input/input.h
- src/main.cpp
- src/modules/vpad/vpad_status.cpp
- src/platform/CMakeLists.txt
- src/platform/platform_glfw_ui.cpp
- src/platform/platform_sdl.h
- src/platform/platform_sdl_input.cpp
- src/platform/platform_sdl_ui.cpp
- src/platform/platform_ui.h
I've tested keyboard and joystick input; I haven't tested graphics beyond opening the window, but that's mostly OpenGL (I think?) so I don't expect this to break anything.
If this is accepted, my intent is to next add support for separate TV and DRC windows, so you could (for example) make the TV window fullscreen on one monitor and have the gamepad window on another monitor. I can also set up a sound output backend, as I see a bit of work is going on in snd_core.
I haven't touched the Visual Studio build since I don't have VS. Hopefully SDL shouldn't be too difficult to pull in there.
> Implement an SDL2-based UI, and use it in CMake builds.

- src/cpu/instructiontable.cpp
- src/cpu/interpreter/interpreter_float.cpp
- src/cpu/interpreter/interpreter_pairedsingle.cpp
- src/fuzztests.cpp
- src/modules/coreinit/coreinit_expheap.cpp
- src/modules/coreinit/coreinit_thread.cpp
- src/modules/coreinit/coreinit_unitheap.cpp
- src/platform/platform_glfw_ui.cpp
- src/platform/platform_sdl_ui.cpp
A few things picked up from adding -Wall. I left some unused variables/functions alone if it looked like they might be useful in the future or as documentation.
> Warning fixes

- src/CMakeLists.txt
- src/debugnet.cpp
- src/filesystem/filesystem_virtual_folder.h
- src/gpu/microcode/latte_blockify.cpp
- src/kernel/kernel_hlemodule.h
- src/main.cpp
- src/modules/CMakeLists.txt
Updates CMakeLists, removes some unnecessary copies and adds includes. Should fix travis-ci build.
> Fixes compile errors on Linux

- src/common/src/platform_posix_fiber.cpp
Changed it from NULL to nullptr to reflect its pointer status.
> Changed NULL in FiberEntryPoint to nullptr

- src/common/src/platform_posix_thread.cpp
- src/common/structsize.h
- src/decaf-sdl/decafsdl.cpp
It seems I only have a moment every few months to take a look at the project, but these were needed to get the current code building on Linux.
FYI, I've also submitted a fix for a race condition in glbinding that caused random crashes on startup, so you may want to update that library.
> Fix Linux build.

- src/libdecaf/src/ppcutils/wfunc_call.h
(Moved from #155 because git is being silly)
> Save and restore CIA across calls from native to PPC code.

- src/libdecaf/src/gpu/opengl/glsl2_alu_reduction.cpp
> opengl: Handle CUBE instructions with more varied operands.

- build/decaf-sdl.vcxproj
- build/decaf-sdl.vcxproj.filters
- build/libdecaf.vcxproj
- build/libdecaf.vcxproj.filters
- src/decaf-cli/config.cpp
- src/decaf-sdl/config.cpp
- src/decaf-sdl/decafsdl.cpp
- src/decaf-sdl/decafsdl.h
- src/decaf-sdl/decafsdl_sound.cpp
- src/decaf-sdl/decafsdl_sound.h
- src/decaf-sdl/main.cpp
- src/libdecaf/decaf_config.h
- src/libdecaf/decaf_sound.cpp
- src/libdecaf/decaf_sound.h
- src/libdecaf/src/decaf.cpp
- src/libdecaf/src/decaf_config.cpp
- src/libdecaf/src/modules/snd_core/snd_core.h
- src/libdecaf/src/modules/snd_core/snd_core_core.cpp
- src/libdecaf/src/modules/snd_core/snd_core_core.h
- src/libdecaf/src/modules/snd_core/snd_core_device.cpp
- src/libdecaf/src/modules/snd_core/snd_core_device.h
- src/libdecaf/src/modules/snd_core/snd_core_enum.h
- src/libdecaf/src/modules/snd_core/snd_core_voice.cpp
- src/libdecaf/src/modules/snd_core/snd_core_voice.h
This gives me approximately the correct output for Xenoblade menu sound effects (ADPCM) and title BGM (streamed ADX, passed to AXVoice as linear PCM). I have no idea how well it will work with any other game.
This is all very much in the experimental stages -- feel free to suggest changes.
> Implement basic sound output via SDL.

- src/libdecaf/src/gpu/opengl/glsl2_tex.cpp
Xenoblade uses this. I don't know how the instruction selects the mipmap to return info for; at the moment I use the first component of the input vector.
> opengl: Implement GET_TEXTURE_INFO.

- src/libdecaf/src/gpu/opengl/opengl_surface.cpp
Also fix the recorded size for cubemap textures (was missing *6).
> opengl: Record the proper size of surfaces based on the pixel format.

- src/decaf-sdl/decafsdl_draw.cpp
The new code uses integer math to ensure that no pixel will ever be dropped,
and at the same time, no useless bar is shown.
It also fixes an assert error because of floating point math, and the worse
one, because of height >> width.
There is a new parameter for an additional border around both screens, but
it's main purpose is to test this code with eg a single pixel line.
No idea about the exact coding style, but I've also dropped "auto". It was
a mixed usage of float and doubles, hard to check which one is of which format.
What do you think about the design ideas:
- aspect is more important than 5px border between TV and DRC
- symmetry is more important than aspect
> decaf-sdl: Rewrite emulated screen position.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
Seems like it could be useful in tracking down shader-related bugs.
> opengl: Dump translated shader code in addition to raw disassembly.

- src/libdecaf/src/gpu/latte_constants.h
- src/libdecaf/src/gpu/opengl/glsl2_exp.cpp
- src/libdecaf/src/gpu/opengl/glsl2_translate.cpp
- src/libdecaf/src/gpu/opengl/glsl2_translate.h
- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
I've checked via apitrace that this gives the correct output format.
> opengl: Transform feedback fixes.

- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
I realize the bitcasts come from the fact that both int and float instructions use the same GPRs, but I still feel that there ought to be a cleaner way to deal with this...
> opengl: Fix handling of integer vertex attributes.

- src/decaf-sdl/decafsdl_draw.cpp
- src/decaf-sdl/main.cpp
Mainly to avoid the case where the config file is invalid, but the program doesn't print any error (because the default is not to log to stdout) and I get confused...
> Logging fixes.

- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
This gives me a solid ~30% speed increase in Xenoblade.
> opengl: Use common logic for uniform, attribute, and feedback buffers.

- src/common/src/platform_posix_exception.cpp
- src/libcpu/src/interpreter/interpreter_loadstore.cpp
- src/libcpu/src/jit/jit.cpp
- src/libcpu/src/jit/jit_loadstore.cpp
Please doublecheck the stack allocation reduction from 0x38 to 0x28 -- all the documentation I've seen says the shadow space size is 0x20 (4 64-bit registers) and I don't see any stack references in generated code, but let me know if this breaks anything on Windows.
> jit: Tweak prologue/epilogue.

- src/libdecaf/src/modules/coreinit/coreinit_debug.cpp
Finally got around to actually checking the behavior of this on console. Xenoblade stack traces make a lot more sense now...
> coreinit: Fix OSGetSymbolName() behavior.

- src/libdecaf/src/gpu/opengl/glsl2_alu.cpp
Verified against R600 API docs and Mesa source.
> opengl: Fix the order of applying OMOD and CLAMP.

- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
> opengl: Reduce apitrace clutter by unbinding unused textures.

- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_pm4.cpp
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
This makes apitrace a _lot_ less painful...
> opengl: Only upload uniform registers which have been recently written.

- src/libdecaf/src/gpu/opengl/opengl_colorbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_depthbuffer.cpp
- src/libdecaf/src/gpu/opengl/opengl_draw.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.cpp
- src/libdecaf/src/gpu/opengl/opengl_driver.h
- src/libdecaf/src/gpu/opengl/opengl_registers.cpp
- src/libdecaf/src/gpu/opengl/opengl_shader.cpp
- src/libdecaf/src/gpu/opengl/opengl_texture.cpp
- src/libdecaf/src/gpu/opengl/opengl_viewport.cpp
FYI, this gives me a performance boost of about 15% on the Xenoblade title screen.
(One of these days I just know I'm going to type Xenogears instead of Xenoblade...)
> opengl: Cache additional GL state data.

- src/libdecaf/src/gpu/gpu_addrlibopt.cpp
The single function AddrComputeSurfaceAddrFromCoord<1, false, 8, 0> was consuming 20% of CPU time (over all threads!) during the Xenoblade intro movie.
I think the ideal end state would be something like a precompiler that generated a big set of optimized routines for each source/dest type pair, or maybe even dynamic code generation, but this at least fixes Xenoblade movies not playing back at full speed.
> gpu: Optimize copying between linear-mode surfaces.

- src/common/bitutils.h
- src/libcpu/espresso/espresso_instruction_definitions.inl
- src/libcpu/src/interpreter/interpreter_float.cpp
- src/libcpu/src/interpreter/interpreter_float.h
- src/libcpu/src/interpreter/interpreter_loadstore.cpp
- src/libcpu/src/interpreter/interpreter_pairedsingle.cpp
Various things I found while working on libbinrec.
FYI, I've also expanded the test suite at http://achurch.org/cpu-tests/ppc750cl.s in case you want to rebuild the associated rpx (there are I think 4 tests which still fail, mostly from lfd+ps_* data corruption).
> Interpreter fixes.

- src/decaf-sdl/config.cpp
- src/decaf-sdl/decafsdl_opengl.cpp
- src/decaf-sdl/decafsdl_opengl.h
- src/libdecaf/decaf_config.h
- src/libdecaf/src/decaf_config.cpp
```
"ui": {
"background_color": {
"red": 153,
"green": 51,
"blue": 51
}
}
```
Resolves #364.
> sdl: Make background color configurable

- CMakeLists.txt
> multiprocessor compilation switch for msvc compilers

- src/libdecaf/src/kernel/kernel_loader.cpp
For a module with a .thrbss section but no .thrdata, the kernel would incorrectly calculate a TLS size of zero.
> kernel: Take .thrbss into account when calculating TLS size.

- src/decaf-cli/main.cpp
- src/decaf-sdl/main.cpp
> Fix typo in libbinrec optimization flag name for --jit-opt-level=1.

- src/libcpu/src/jit/binrec/jit_binrec.cpp
Issue: https://github.com/decaf-emu/decaf-emu/issues/456
> Fix a crash in jit_binrec.cpp

- tests/cpu/runner-achurch/main.cpp
> tests: Correct 'disasembly'

- src/decaf-qt/mainwindow.cpp
- src/decaf-qt/mainwindow.h
- src/decaf-qt/ui/mainwindow.ui
Added a "Full Screen" option to the View menu.  Also plumbed in the F11 key to toggle between full screen mode and back.
> Added a menu option to go into full screen mode.

- src/decaf-qt/mainwindow.cpp
Fix compilation under Linux and other case-sensitive systems
> Fix case-sesitivity issue

- src/common-sdl/decafsdl_vulkan.cpp
Before this commit, decaf was crashing, raising an `ErrorExtensionNotPresent` exception. This commit logs missing extensions before letting decaf quitting.
> Check vulkan extensions are available when creating device

- src/libdecaf/src/ios/fpd/ios_fpd_act_accountdata.cpp
To be able to compile it in Arch Linux using PKGBUILD
> Add missing include

- BUILDING.md
A couple were missing in order to build successfully
> Update suggested apt dependencies for Linux

- src/libdecaf/src/cafe/libraries/nn_boss/nn_boss_nbdltasksetting.cpp
Likely just a copypasta error. Fix allows PUYOPUYOTETRIS to boot.
> cafe/nn_boss: Fix conditional in NbdlTaskSetting_Initialize

- .github/workflows/ccpp.yml
Use Variables to set:
MSVC version
Compiler & version
vulkan version
qt-version
> Rewrite yaml with env vars
